name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Build Next.js Project
      run: npm run build

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_PATH: ${{ secrets.EC2_PATH }}
      run: |
        # Save the SSH key to a file
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > rg_key.pem
        chmod 600 rg_key.pem

        # Deploy using the correct SSH key reference
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << EOF
          cd $EC2_PATH
          git pull origin main
          npm install
          npm run build
          pm2 restart next-app || pm2 start npm --name "next-app" -- start
        EOF

        # Cleanup
        rm -f private_key.pem