name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Build Next.js Project
      run: npm run build

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_PATH: ${{ secrets.EC2_PATH }}
      run: |
        # Save the SSH key correctly
        printf "%s" "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # Debug: Check if key file exists
        ls -lah private_key.pem

        # Debug: Test SSH connection before running commands
        ssh -v -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "echo 'Connected successfully!'"

        # Deploy using SSH
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          set -e  # Exit on any error

          [ -d "$EC2_PATH" ] || mkdir -p "$EC2_PATH"
          cd "$EC2_PATH"

          git pull origin main || (echo "Git pull failed" && exit 1)
          npm install --production
          npm run build

          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

          pm2 restart next-app || pm2 start npm --name "next-app" -- start
        EOF

        # Cleanup SSH key
        rm -f private_key.pem